[theme]
primaryColor = "#003056"

[theme.light]
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E8E8E8"
textColor = "#000000"
dataframeBorderColor = "#888888"
dataframeHeaderBackgroundColor = "#E8E8E8"

[theme.light.sidebar]
backgroundColor = "#003056"
textColor = "#FFFFFF"

[theme.dark]
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFFFFF"

[theme.dark.sidebar]
backgroundColor = "#0A0A0A"
textColor = "#FFFFFF"
